// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Song = 1,
  Line = 2,
  Metadata = 3,
  MetadataKey = 4,
  MetadataValue = 5,
  Environment = 6,
  EnvironmentStartKey = 7,
  EnvironmentLabel = 8,
  EnvironmentEndKey = 9
