// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,title:36, t:36, subtitle:36, st:36, artist:36, key:36, tempo:36, time:36, comment:36, c:36, comment_italic:36, ci:36, comment_box:36, cb:36, start_of_chorus:42, soc:42, start_of_verse:42, sov:42, start_of_tab:42, sot:42, end_of_chorus:46, eoc:46, end_of_verse:46, eov:46, end_of_tab:46, eot:46}
export const parser = LRParser.deserialize({
  version: 14,
  states: "$[QVQPOOObQQO'#C^OgQPO'#CcOOQO'#Ci'#CiOOQO'#Ce'#CeQVQPOOOrQSO'#C`OzQPO,58xOOQO,58},58}OgQPO,58}O!PQSO'#C`OOQO-E6c-E6cO![QSO,58zO!dQWO,59[OOQO1G.d1G.dOOQO1G.i1G.iO!lQPO,59^OOQO1G.f1G.fO!qQWO1G.fOOQO1G.v1G.vO!vQPO1G.vOOQO1G.x1G.xO!{QPO7+$QOOQO7+$b7+$bOOQO<<Gl<<Gl",
  stateData: "#X~O[OS~OWRO_POaUO~ORVO~OWRO_POaYO~Ob[Oe]O~O^^O~Ob[Oe]Og`O~O`aOcbO~OUdO`cO~O`eO~OUfO~O`gO~O`hO~O[TRUWU~",
  goto: "![gPPhPhPPhPnPPPxPPPPPP!OP!UXROQTXQTOQXQTZTXXSOQTXXQOQTXQWQR_X",
  nodeNames: "⚠ Song Chord ChordContent Directive Identifier DirectiveValueText Environment Text",
  maxTerm: 23,
  skippedNodes: [0,5],
  repeatNodeCount: 1,
  tokenData: ",u~RhOX!mXY%{YZ'`Z]!m]^'`^p!mpq%{q![!m![!]'q!]!c!m!c!}(u!}#O*V#O#P!m#P#Q*{#Q#R!m#R#S(u#S#T!m#T#o(u#o#p+f#p#q!m#q#r,[#r;'S!m;'S;=`%u<%lO!mZ!v]RQUWWPOY!mZ]!m^!}!m!}#O#o#O#P!m#P#Q$c#Q#o!m#o#p#o#p#q!m#q#r%Q#r;'S!m;'S;=`%u<%lO!mY#vXRQUWOY#oZ]#o^#P#o#P#Q$c#Q#q#o#q#r%Q#r;'S#o;'S;=`%o<%lO#oW$hUUWOY$cZ]$c^#q$c#r;'S$c;'S;=`$z<%lO$cW$}P;=`<%l$cQ%VURQOY%QZ]%Q^#P%Q#Q;'S%Q;'S;=`%i<%lO%QQ%lP;=`<%l%QY%rP;=`<%l#oZ%xP;=`<%l!m~&Wb[~RQUWWPOX!mXY%{YZ'`Z]!m]^'`^p!mpq%{q!}!m!}#O#o#O#P!m#P#Q$c#Q#o!m#o#p#o#p#q!m#q#r%Q#r;'S!m;'S;=`%u<%lO!m~'eS[~XY'`YZ'`]^'`pq'`_'|]cSRQUWWPOY!mZ]!m^!}!m!}#O#o#O#P!m#P#Q$c#Q#o!m#o#p#o#p#q!m#q#r%Q#r;'S!m;'S;=`%u<%lO!m_)QaTSRQUWWPOY!mZ]!m^!c!m!c!}(u!}#O#o#O#P!m#P#Q$c#Q#R!m#R#S(u#S#T!m#T#o(u#o#p#o#p#q!m#q#r%Q#r;'S!m;'S;=`%u<%lO!mZ*`X_PRQUWOY#oZ]#o^#P#o#P#Q$c#Q#q#o#q#r%Q#r;'S#o;'S;=`%o<%lO#oX+SU^PUWOY$cZ]$c^#q$c#r;'S$c;'S;=`$z<%lO$cZ+oXaPRQUWOY#oZ]#o^#P#o#P#Q$c#Q#q#o#q#r%Q#r;'S#o;'S;=`%o<%lO#o_,cU`]RQOY%QZ]%Q^#P%Q#Q;'S%Q;'S;=`%i<%lO%Q",
  tokenizers: [0, 1, 2, 3],
  topRules: {"Song":[0,1]},
  specialized: [{term: 5, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 94
})
