// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Song = 1,
  Chord = 2,
  ChordContent = 3,
  Directive = 4,
  Identifier = 5,
  DirectiveValueText = 6,
  Environment = 7,
  Text = 8
